"""
Gera Components/Icons/RvmIconData.cs a partir dos SVGs do Phosphor.

Rodar so quando a lista de icones mudar:
    python tools/gerar-icones.py <pasta-com-svgs>

O resultado e COMMITADO. O build nao baixa nada e nao depende de rede — reconstruir o
pacote offline continua funcionando, e o conjunto de icones fica visivel em code review
em vez de aparecer por magica no CI.
"""
import re, sys, pathlib, collections

# A lista e CURADA, nao o conjunto inteiro do Phosphor (1512 icones). Cada nome aqui vira
# API publica e bytes que todo consumidor baixa. Icone entra quando um componente precisa,
# nunca "porque pode ser util" — a regra esta no `03-arquitetura.md` § Icones.
ICONES = [
    # Onda 1 — formulario e estado
    'check', 'x', 'caret-down', 'caret-up', 'eye', 'eye-slash',
    'warning', 'info', 'circle-notch', 'magnifying-glass', 'calendar-blank',
    # Onda 2 — layout e navegacao
    'list',                  # menu hamburguer do RvmTopbar no mobile
    'caret-right',           # separador do RvmBreadcrumb e seta do RvmNavItem com filhos
    'caret-left',            # voltar
    'sidebar-simple',        # colapsar/expandir o RvmSidebar
    'user',                  # fallback do RvmAvatar sem imagem nem iniciais
    'house',                 # item de navegacao mais comum
    'dots-three-vertical',   # menu de acoes secundarias
    'copy',                  # botao de copiar do bloco de codigo (site de documentacao)
    # Onda 3 — feedback
    'check-circle',          # severidade Success no RvmAlert e no RvmToast
    'x-circle',              # severidade Danger (o `warning` triangular fica com Warning)
    'lock',                  # RvmEmptyState, variante "sem permissao"
    'tray',                  # RvmEmptyState, variante "vazio"
]

origem = pathlib.Path(sys.argv[1])
dados = collections.OrderedDict()

for nome in ICONES:
    for peso in ('regular', 'fill'):
        arq = origem / f'{nome}-{peso}.svg'
        svg = arq.read_text(encoding='utf-8')
        corpo = re.sub(r'^.*?<svg[^>]*>', '', svg, flags=re.S)
        corpo = re.sub(r'</svg>\s*$', '', corpo, flags=re.S).strip()
        # fill="currentColor" ja vem no <svg> raiz do Phosphor; no <path> ele e redundante
        # e atrapalha quando o consumidor quer pintar por CSS.
        corpo = corpo.replace(' fill="currentColor"', '')
        dados[(nome, peso)] = corpo

linhas = []
for (nome, peso), corpo in dados.items():
    linhas.append(f'        ["{nome}:{peso}"] = """{corpo}""",')

pathlib.Path('src/RVM.DesignSystem/Components/Icons/RvmIconData.cs').write_text(
'''// <auto-generated>
//     GERADO por tools/gerar-icones.py a partir dos SVGs do Phosphor (MIT).
//     Nao editar a mao — rodar o script de novo quando a lista de icones mudar.
// </auto-generated>

using System.Collections.Frozen;

namespace RVM.DesignSystem.Components;

/// <summary>Os desenhos dos icones, por nome e peso.</summary>
internal static class RvmIconData
{
    /// <summary>Todos os icones do conjunto, chaveados por <c>nome:peso</c>.</summary>
    internal static readonly FrozenDictionary<string, string> Todos = new Dictionary<string, string>(StringComparer.Ordinal)
    {
''' + '\n'.join(linhas) + '''
    }.ToFrozenDictionary(StringComparer.Ordinal);

    /// <summary>Os nomes disponiveis, para a pagina de icones do site e para a mensagem de erro.</summary>
    internal static readonly IReadOnlyList<string> Nomes =
    [
''' + '\n'.join(f'        "{n}",' for n in ICONES) + '''
    ];
}
''', encoding='utf-8', newline='\n')

print(f'gerado: {len(dados)} desenhos, {len(ICONES)} icones x 2 pesos')
