# Icones do contrato com o RVM.UI (DSGN-017): os nomes Solar do RvmIconName do RVM.UI, desenhados com Tabler.
#
#   python -I tools/icones-do-contrato.py <pasta icons do pacote @tabler/icons>
#
# Le tools/icones-do-contrato.json ({"NomeSolar": "nome-tabler"}, revisado a mao) e gera:
#   - os membros do RvmIconName depois do marcador (o resto do arquivo e escrito a mao);
#   - Icons/RvmIconCatalogo.Contrato.g.cs: o traco e o desenho cheio de cada icone Tabler usado.
# O desenho cheio vale para os 46 icones de antes tambem: o nome Tabler deles sai comparando o traco guardado.
import json
import re
import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
ICONES = RAIZ / "src" / "RVM.DesignSystem" / "Icons"
MARCADOR = "    // --- Gerado por tools/icones-do-contrato.py a partir daqui: nao editar a mao. ---"


def miolo(svg: str) -> str:
    corpo = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1)
    corpo = re.sub(r'<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*/>', "", corpo)
    return " ".join(e.strip() for e in re.findall(r"<[^>]+>", corpo))


def normal(markup: str) -> str:
    return re.sub(r"\s+", "", markup).replace("/>", ">")


def cs(texto: str) -> str:
    return '"""' + texto + '"""'


def main(pasta_tabler: str) -> None:
    tabler = Path(pasta_tabler)
    mapa = json.loads((RAIZ / "tools" / "icones-do-contrato.json").read_text(encoding="utf-8"))

    def traco(nome):
        return miolo((tabler / "outline" / f"{nome}.svg").read_text(encoding="utf-8"))

    def cheio(nome):
        arquivo = tabler / "filled" / f"{nome}.svg"
        return miolo(arquivo.read_text(encoding="utf-8")) if arquivo.exists() else None

    # Os 46 de antes: o nome Tabler sai do traco que o RvmIconCatalogo.cs ja guarda.
    catalogo = (ICONES / "RvmIconCatalogo.cs").read_text(encoding="utf-8")
    por_traco = {normal(traco(p.stem)): p.stem for p in (tabler / "outline").glob("*.svg")}
    antigos = {}
    for nome, desenho in re.findall(r'\[RvmIconName\.(\w+)\] = """(.*?)"""', catalogo):
        antigos[nome] = por_traco.get(normal(desenho))

    usados = sorted(set(mapa.values()))
    cheios = {n: c for n in sorted(set(usados) | {v for v in antigos.values() if v}) if (c := cheio(n))}

    linhas = [
        "// <auto-generated> tools/icones-do-contrato.py (Tabler " + (tabler.parent / "package.json").read_text(encoding="utf-8").split('"version": "')[1].split('"')[0] + "). Nao editar a mao. </auto-generated>",
        "using System.Collections.Frozen;",
        "",
        "namespace RVM.DesignSystem.Icons;",
        "",
        "internal static partial class RvmIconCatalogo",
        "{",
        "    /// <summary>Nome do contrato (Solar, do RVM.UI) para o icone Tabler que o desenha.</summary>",
        "    private static readonly FrozenDictionary<RvmIconName, string> TablerDoContrato = new Dictionary<RvmIconName, string>",
        "    {",
        *[f'        [RvmIconName.{s}] = "{t}",' for s, t in sorted(mapa.items())],
        "    }.ToFrozenDictionary();",
        "",
        "    /// <summary>Nome Tabler dos icones de antes do contrato, para achar o desenho cheio.</summary>",
        "    private static readonly FrozenDictionary<RvmIconName, string> TablerDosAntigos = new Dictionary<RvmIconName, string>",
        "    {",
        *[f'        [RvmIconName.{s}] = "{t}",' for s, t in sorted(antigos.items()) if t],
        "    }.ToFrozenDictionary();",
        "",
        "    /// <summary>Traco (outline) de cada icone Tabler usado pelo contrato.</summary>",
        "    private static readonly FrozenDictionary<string, string> Tracos = new Dictionary<string, string>",
        "    {",
        *[f'        ["{n}"] = {cs(traco(n))},' for n in usados],
        "    }.ToFrozenDictionary();",
        "",
        "    /// <summary>Desenho cheio (filled), so dos icones que o Tabler tem cheios.</summary>",
        "    private static readonly FrozenDictionary<string, string> Cheios = new Dictionary<string, string>",
        "    {",
        *[f'        ["{n}"] = {cs(c)},' for n, c in cheios.items()],
        "    }.ToFrozenDictionary();",
        "}",
        "",
    ]
    (ICONES / "RvmIconCatalogo.Contrato.g.cs").write_text("\n".join(linhas), encoding="utf-8", newline="\n")

    enum = (ICONES / "RvmIconName.cs").read_text(encoding="utf-8")
    # Sem o marcador (primeira geracao), o arquivo ainda fecha o enum: a chave sai para os membros entrarem.
    cabeca = enum.split(MARCADOR)[0].rstrip() if MARCADOR in enum else enum.rstrip().removesuffix("}").rstrip()
    if not cabeca.endswith(","):
        cabeca += ","
    membros = [
        f"    /// <summary>Icone <c>{s}</c> do contrato com o RVM.UI, desenhado com o <c>{t}</c> do Tabler.</summary>\n    {s},"
        for s, t in sorted(mapa.items())
    ]
    corpo = "\n\n".join(membros).rstrip(",")
    (ICONES / "RvmIconName.cs").write_text(cabeca + "\n\n" + MARCADOR + "\n\n" + corpo + "\n}\n", encoding="utf-8", newline="\n")

    sem_nome = [n for n, t in antigos.items() if not t]
    print(f"{len(mapa)} nomes do contrato, {len(usados)} desenhos Tabler, {len(cheios)} cheios; antigos sem nome Tabler: {sem_nome}")


if __name__ == "__main__":
    main(sys.argv[1])
